### ISSUE TITLE
Consider targeting more specific areas that could throw

### ISSUE THREAD

**Issue by GrosSacASac** [ujjwalguptaofficial/fortjs#1]
https://github.com/ujjwalguptaofficial/fortjs/blob/master/src/handlers/request_handler.ts#L111

I consider putting a huge chunk of lines of code inside a `try catch` an anti-pattern.

**Comment by ujjwalguptaofficial** [comment]
Thanks for bringing this out. I consider those bad too.

I will try to split those.

**Comment by ujjwalguptaofficial** [comment]
fixed and release in new version - 1.5.6.
