### ISSUE TITLE
Feature Request : The status code of the response should be available in the Wall

### ISSUE THREAD

**Issue by faiztherocker** [ujjwalguptaofficial/fortjs#18]
Wall's Outgoing function is the right place to create to create a generic 500 caught exception handler in fortjs, however the as per the current implementation the status code of the response is not available in response object available in the Wall.

> Request you to add status code to the response object.

**Comment by ujjwalguptaofficial** [comment]
Added in new version - 1.14.0. Now outgoing event of wall will be called with final result of type [HttpResult](https://fortjs.info/tutorial/type/http-result/)

so whatever result is returned from controller, shield or any component will be passed to wall outgoing.

e.g - 

```
class AppWall extends Wall {
    async onIncoming() {
        return null;
    }

    async onOutgoing(result) {
        if(result.statusCode===200){
           // do something 
       }
    }
}
```

You can also modify final result if you want like this -  

```
class AppWall extends Wall {
    async onIncoming() {
        return null;
    }

    async onOutgoing(result) {
       Object.assign(result, textResult("result modified by wall outgoing");
    }
}
```
