### ISSUE TITLE
Feature Request: Adding type to HttpResult

### ISSUE THREAD

**Issue by faiztherocker** [ujjwalguptaofficial/fortjs#19]
Currently the HttpResult has a property "responseData" which is of type any, This feature request is to add  type support in HttpResult<T> so that the user of the library could pass the DTO class type for the "responseData" object.

**Comment by ujjwalguptaofficial** [comment]
But what would someone achieve by having a type in responseData of HttpResult ? Any use case ?

**Comment by faiztherocker** [comment]
Well this is for the maintainability and readability of the code. This would ensure that devs are only forwarding DTOs to frontend.

**Comment by ujjwalguptaofficial** [comment]
Good point but adding this to framework itself is not a good idea as it might confuse some users. I will suggest you to create a wrapper in your code to return different types of result.

e.g - 

```
function getResult<T>(result){
   return jsonResult(result);
}
```
