### ISSUE TITLE
Async Promise antipattern is used

### ISSUE THREAD

**Issue by GrosSacASac** [ujjwalguptaofficial/fortjs#2]
On this line https://github.com/ujjwalguptaofficial/fortjs/blob/master/src/handlers/request_handler.ts#L185

```
    async handlePostData() {
        if (this.request.method === HTTP_METHOD.Get) {
            this.body = {};
        }
        else if (Global.shouldParsePost === true) {
            try {
                this.body = await this.parsePostData();
            }
            catch (ex) {
                return Promise.reject(ex);
            }
        }
    }
```

Things to know about Promises: 
1. Promises are flattened by default. (Think flat map). So:
`Promise.reject(Promise.reject("error"))` is the same as `Promise.reject("error")` and `Promise.resolve(Promise.resolve("value"))` is the same as `Promise.resolve("value")`
`Promise.resolve(Promise.reject("error"))` is the same as `Promise.reject("error")`
 2. Async function will wrap any **returned value** in a `Promise.resolve` and any **thrown value** in a `Promise.reject` 

So inside the else if it could be rewritten

```
            try {
                this.body = await this.parsePostData();
            }
            catch (ex) {
                throw ex;
            }
```

3. Also, any function that throws will propagate the error down the stack trace until a catch is found. It means it is useless to have `catch (x) { throw x;}`

So even simpler

```
`this.body = await this.parsePostData();            
```

The code will execute the same. Next steps fix other places that use this antipattern

**Comment by ujjwalguptaofficial** [comment]
Thanks for your valuable suggestion @GrosSacASac . I used to follow what you have suggested, but there was some issue happened in one of my projects & that's why i started using Promise.reject. But anyway what you have explained seems to work nice, so i will take your suggestion and will get rid of antipattern practice.

**Comment by GrosSacASac** [comment]
At the end of the day it is your choice, I would be happy to learn something if you can prove me wrong.

**Comment by ujjwalguptaofficial** [comment]
My aim is to make this project very solid & your knowledge is helping me to achieve those. So feel free to suggest other things.

Thanks
