### ISSUE TITLE
Feature Request: Allow ErrorHandler methods to return Promise<HttpResult>

### ISSUE THREAD

**Issue by faiztherocker** [ujjwalguptaofficial/fortjs#23]
Allow the methods of ErrorHandler class to return `Promise<HttpResult>` rather than `Promise<string>`. This gives the flexibility to the users to either return a jsonResult or a textResult.

**Comment by ujjwalguptaofficial** [comment]
fixed in v-1.15.0 . Now you can return result of type HttpResult | HttpFormatResult from custom error handler.

All custom error events will call wallOutgoing except internalServerError.
