### ISSUE TITLE
Feature Request: Allow fortjs server to be hosted on https

### ISSUE THREAD

**Issue by faiztherocker** [ujjwalguptaofficial/fortjs#24]
Though this is not an industry standards, hosting of the server on https might be required for demonstration purposes.

**Comment by ujjwalguptaofficial** [comment]
Feature support is added in new version - 1.13.1. Here is an example - https://github.com/ujjwalguptaofficial/fortjs-examples/tree/master/https

Basically you can create your own http server and assign to fort & then fort will use that http server.
