### ISSUE TITLE
Not working with many checkbox radio ?

### ISSUE THREAD

**Issue by alexandre-solymos** [ujjwalguptaofficial/fortjs#32]
Hello i need help,
I would like use many checkbox but when i click to checkbox one and checkbox two is not working.

I have a form with a lot of radio buttons they are all in classes
The problem is that when I click on the first radio button it works but when I click on the second one and well the Progress bar doesn't advance.
and I can have forms with 10 checkboxes as 6 is random how to make it automatic?

`[]( check -->https://jsfiddle.net/alex447/m6juh0dx/19/ )
`

`  function flash(){
function cback(e) {
    var t = [];
    for (var n = inputs.length; n--;) {
        if (!inputs[n].value.length) t.push(inputs[n]);
    }
    var r = t.length;
    var i = inputs.length;
    var s = document.querySelectorAll(".top");
    for (var o = s.length; o--;) {
        s[o].style.width = 100 - r / i * 100 + "%";
        s[o].style.background = cols[i-r-1];
    }
}
var forms = document.querySelectorAll(".form"),
    inputs = [];
for (var i = forms.length; i--;) {
    var els = forms[i].querySelectorAll("input, textarea, select");
    for (var j = els.length; j--;) {
        if (els[j].type != "button" && els[j].type != "submit") {
            inputs.push(els[j]);
            els[j].addEventListener("input", cback, false);
        }
    }
}

var cols = ["#1ABC9C","#EC7063","#3498DB"];
}

function gradient(){
    function cback(e) {
    var t = [];
    for (var n = inputs.length; n--;) {
        if (!inputs[n].value.length) t.push(inputs[n]);
    }
    var r = t.length;
    var i = inputs.length;
    var s = document.querySelectorAll(".top");
    for (var o = s.length; o--;) {
        s[o].style.width = 100 - r / i * 100 + "%";
    }
}
var forms = document.querySelectorAll(".form"),
    inputs = [];
for (var i = forms.length; i--;) {
    var els = forms[i].querySelectorAll("input, textarea, select");
    for (var j = els.length; j--;) {
        if (els[j].type != "button" && els[j].type != "submit") {
            inputs.push(els[j]);
            els[j].addEventListener("input", cback, false);
        }
    }
}
}
function sections(){
    function cback(e) {
    var t = [];
    for (var n = inputs.length; n--;) {
        if (!inputs[n].value.length) t.push(inputs[n]);
    }
    var r = t.length;
    var i = inputs.length;
    var s = document.querySelectorAll(".top");
    for (var o = s.length; o--;) {
        s[o].style.width = 100 - r / i * 100 + "%";
    }
}
var forms = document.querySelectorAll(".form"),
    inputs = [];
for (var i = forms.length; i--;) {
    var els = forms[i].querySelectorAll("input, radio, select");
    for (var j = els.length; j--;) {
        if (els[j].type != "button" && els[j].type != "submit") {
            inputs.push(els[j]);
            els[j].addEventListener("input", cback, false);
        }
    }
}

function generateCSSGradient(colours) {
    var l = colours.length, i;
    for( i=0; i<l; i++) colours[i] = colours[i].join(" ");
    return "linear-gradient( to right, "+colours.join(", ")+")";
}

var cols = [
    ["#1ABC9C","0%"],
    ["#1ABC9C","33.3%"],
    ["#EC7063","33.3%"], // note same percentage - this gives a crisp change
    ["#EC7063","66.6%"],
    ["#3498DB","66.6%"],
    ["#3498DB","100%"]
];
    document.getElementsByClassName('.top').innerHTML = '<div class="colors"></div>';
document.querySelector(".colors").style.background = generateCSSGradient(cols);

var window_width = window.innerWidth + "px";
document.querySelector(".colors").style.width = window_width;

  
};`

Thanks

**Comment by ujjwalguptaofficial** [comment]
I don't understand - this is not related to fortjs anywhere.
