### ISSUE TITLE
Dependency injection stops working when using more than 2 singletons in a controller

### ISSUE THREAD

**Issue by TimWelter** [ujjwalguptaofficial/fortjs#4]
I have 3 services right now that I need to inject into my controller. Problem is when I use a third one it'll just stop injecting all together.
Example:

    getOrderService: GetOrderService
    updateOrderService: UpdateOrderService
    createOrderService: CreateOrderService

    constructor(
        @Singleton(CreateOrderService) createOrderService: CreateOrderService,
        @Singleton(GetOrderService) getOrderService: GetOrderService,
        @Singleton(UpdateOrderService) updateOrderService: UpdateOrderService) {
              super();
              this.getOrderService = getOrderService;
              this.createOrderService = createOrderService;
              this.updateOrderService = updateOrderService;
    }

returns on every request:
`internal server error
message : this.getOrderService.<<whatever.function.is.called>> is not a function
stacktrace: TypeError: this.getOrderService.<<whatever.function.is.called>> is not a function at OrderController. (C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:285:60) at step (C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:221:23) at Object.next (C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:202:53) at C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:196:71 at new Promise () at ./controllers/order_controller.ts.__awaiter (C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:192:12) at OrderController../controllers/order_controller.ts.OrderController.<<whatever.function.is.called>>(C:\Users\weltert\Desktop\pba-api-test\pba-api\bin\app.js:281:16) at RequestHandler.module.exports.RequestHandler.runController_ (C:\Users\weltert\Desktop\pba-api-test\pba-api\node_modules\fortjs\dist\fort.js:2162:67) at RequestHandler. (C:\Users\weltert\Desktop\pba-api-test\pba-api\node_modules\fortjs\dist\fort.js:2322:34) at step (C:\Users\weltert\Desktop\pba-api-test\pba-api\node_modules\fortjs\dist\fort.js:2069:23) at Object.next (C:\Users\weltert\Desktop\pba-api-test\pba-api\node_modules\fortjs\dist\fort.js:2050:53) at fulfilled (C:\Users\weltert\Desktop\pba-api-test\pba-api\node_modules\fortjs\dist\fort.js:2041:58) `

But if I remove 1 singleton (doesn't matter which):

    getOrderService: GetOrderService
    updateOrderService: UpdateOrderService

    constructor(
        @Singleton(CreateOrderService) createOrderService: CreateOrderService,
        @Singleton(GetOrderService) getOrderService: GetOrderService) {
           super();
              this.getOrderService = getOrderService;
              this.createOrderService = createOrderService;
    }

It'll work just fine.

**Comment by ujjwalguptaofficial** [comment]
Thanks Tim for adding this issue.

I will look into it and fix asap.

Thanks & Regards
Ujjwal

**Comment by TimWelter** [comment]
Should mention that I found out not **all** injected services stop working but just 1. So far it seems to be random which one.

**Comment by ujjwalguptaofficial** [comment]
but not all working at a time right ?

**Comment by TimWelter** [comment]
Nope

**Comment by ujjwalguptaofficial** [comment]
nope, i just created a project with three singletons but cant reproduce. Will share the project in a minute

**Comment by ujjwalguptaofficial** [comment]
Check this out - https://github.com/ujjwalguptaofficial/fortjs-issues-project/tree/master/multiple-dependency-injection-not-working

Feel free to change something & reproduce. If you are able reproduce, send the PR.

Thanks

**Comment by TimWelter** [comment]
I'll check it out though I haven't been able to reproduce it so far.

**Comment by TimWelter** [comment]
Added a pull request

**Comment by ujjwalguptaofficial** [comment]
Yeah, i can confirm - singletons are being mixed up :(. I will fix it.

**Comment by ujjwalguptaofficial** [comment]
Fixed in v - 1.8.3, please test and confirm.

And really thanks for founding such an issue :).

**Comment by TimWelter** [comment]
Works great. Thank you very much!
